# Generated by Django 5.0.1 on 2024-02-02 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_reading_request_ip_datalogger_reading_data_logger'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogger',
            name='lastActive',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
