# Generated by Django 5.0.1 on 2024-02-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_datalogger_lastactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogger',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
