# Generated by Django 5.0.1 on 2024-01-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.PositiveIntegerField()),
                ('raw_reading', models.PositiveIntegerField()),
                ('co2_ppm', models.PositiveIntegerField()),
            ],
        ),
    ]
