# Generated by Django 5.0.3 on 2024-03-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0002_location_datalogger_reading_locations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reading",
            old_name="locations",
            new_name="location",
        ),
        migrations.AddField(
            model_name="location",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
